/**
 * @nai/qa-loop — Programmatic QA Loop
 *
 * Provides functions to run QA verification programmatically,
 * read QA loop history, and generate upgrade reports.
 *
 * Used by:
 * - @nai/self-heal: verify fixes before requesting approval
 * - Console: display QA status
 * - API: expose QA endpoints
 */

import { execSync } from 'node:child_process';
import { readFileSync, existsSync, appendFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

// ============================================================
// Types
// ============================================================

export interface QAResult {
  step: string;
  passed: boolean;
  detail: string;
  durationMs: number;
}

export interface QALoopResult {
  loopNumber: number;
  timestamp: string;
  results: QAResult[];
  allGreen: boolean;
  durationMs: number;
}

export interface UpgradeReportEntry {
  date: string;
  event: string;
  commits: number;
  filesChanged: number;
  auditStatus: string;
  typecheckStatus: string;
  buildStatus: string;
  testStatus: string;
  overall: string;
}

// ============================================================
// Core: runQALoop
// ============================================================

export function runQALoop(cwd?: string): QALoopResult {
  const root = cwd ?? process.cwd();
  const timestamp = new Date().toISOString();
  const startTime = Date.now();

  const logPath = join(root, 'QA_LOOP_LOG.md');
  const loopNumber = existsSync(logPath)
    ? (readFileSync(logPath, 'utf8').match(/^## QA Loop/gm)?.length ?? 0) + 1
    : 1;

  const results: QAResult[] = [];

  // Step 1: audit:all
  results.push(runStep('audit:all', 'pnpm run audit:all', root));

  // Step 2: typecheck
  results.push(runStep('typecheck', 'pnpm run typecheck', root));

  // Step 3: build
  results.push(runStep('build', 'pnpm run build', root));

  // Step 4: test
  results.push(runStep('test', 'pnpm run test', root));

  const allGreen = results.every((r) => r.passed);
  const durationMs = Date.now() - startTime;

  const loopResult: QALoopResult = {
    loopNumber,
    timestamp,
    results,
    allGreen,
    durationMs,
  };

  // Append to log
  appendQALoopLog(logPath, loopResult);

  return loopResult;
}

function runStep(name: string, command: string, cwd: string): QAResult {
  const start = Date.now();
  try {
    const output = execSync(command, { cwd, encoding: 'utf8', timeout: 300000, stdio: 'pipe' });
    const durationMs = Date.now() - start;
    let detail = '';
    if (name === 'build' || name === 'test') {
      const tasksLine = output.split('\n').find((l) => l.includes('Tasks:'));
      detail = tasksLine?.trim() ?? 'completed';
    } else {
      detail = 'passed';
    }
    return { step: name, passed: true, detail, durationMs };
  } catch (err) {
    const durationMs = Date.now() - start;
    const errorOutput = (err as { stderr?: string; stdout?: string });
    const detail = (errorOutput.stderr || errorOutput.stdout || String(err))
      .split('\n')
      .filter((l: string) => l.match(/FAIL|error|ERROR|❌/i))
      .slice(0, 5)
      .join('; ');
    return { step: name, passed: false, detail, durationMs };
  }
}

function appendQALoopLog(logPath: string, result: QALoopResult): void {
  const lines: string[] = [
    '',
    `## QA Loop #${result.loopNumber} — ${result.timestamp}`,
    '',
    '| Step | Result | Detail | Duration |',
    '|------|--------|--------|----------|',
  ];

  for (const r of result.results) {
    const status = r.passed ? '✅ PASS' : '❌ FAIL';
    lines.push(`| ${r.step} | ${status} | ${r.detail} | ${r.durationMs}ms |`);
  }

  lines.push('');
  lines.push(result.allGreen ? '**OVERALL: ✅ ALL GREEN**' : '**OVERALL: ❌ HAS FAILURES**');
  lines.push('');
  lines.push('---');
  lines.push('');

  if (!existsSync(logPath)) {
    writeFileSync(logPath, '# QA Loop Log\n\nContinuous QA verification log. Generated by `tools/qa-loop.sh` or `@nai/qa-loop`.\n');
  }
  appendFileSync(logPath, lines.join('\n'));
}

// ============================================================
// History: getQALoopHistory
// ============================================================

export function getQALoopHistory(cwd?: string): QALoopResult[] {
  const root = cwd ?? process.cwd();
  const logPath = join(root, 'QA_LOOP_LOG.md');
  if (!existsSync(logPath)) return [];

  const content = readFileSync(logPath, 'utf8');
  const loops: QALoopResult[] = [];
  const sections = content.split(/^## QA Loop/m).slice(1);

  for (const section of sections) {
    const numMatch = section.match(/#(\d+)/);
    const dateMatch = section.match(/(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z)/);
    const allGreen = section.includes('ALL GREEN');

    const results: QAResult[] = [];
    const rows = section.matchAll(/\| (\w+) \| (✅ PASS|❌ FAIL) \| (.+?) \|/g);
    for (const row of rows) {
      results.push({
        step: row[1] ?? '',
        passed: (row[2] ?? '') === '✅ PASS',
        detail: row[3] ?? '',
        durationMs: 0,
      });
    }

    loops.push({
      loopNumber: numMatch ? parseInt(numMatch[1] ?? '0') : 0,
      timestamp: dateMatch ? (dateMatch[1] ?? '') : '',
      results,
      allGreen,
      durationMs: 0,
    });
  }

  return loops;
}

// ============================================================
// History: getSelfUpgradeHistory
// ============================================================

export function getSelfUpgradeHistory(cwd?: string): UpgradeReportEntry[] {
  const root = cwd ?? process.cwd();
  const historyPath = join(root, 'docs/governance/SELF_UPGRADE_HISTORY.md');
  if (!existsSync(historyPath)) return [];

  const content = readFileSync(historyPath, 'utf8');
  const entries: UpgradeReportEntry[] = [];
  const rows = content.matchAll(/\| (\d{4}-\d{2}-\d{2}) \| (.+?) \| (\d+) \| (\d+) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \| (.+?) \|/g);

  for (const row of rows) {
    entries.push({
      date: row[1] ?? '',
      event: row[2] ?? '',
      commits: parseInt(row[3] ?? '0'),
      filesChanged: parseInt(row[4] ?? '0'),
      auditStatus: row[5] ?? '',
      typecheckStatus: row[6] ?? '',
      buildStatus: row[7] ?? '',
      testStatus: row[8] ?? '',
      overall: row[9] ?? '',
    });
  }

  return entries;
}

// ============================================================
// Report: generateUpgradeReport
// ============================================================

export function generateUpgradeReport(cwd?: string): string {
  const root = cwd ?? process.cwd();
  const date = new Date().toISOString().split('T')[0];
  const reportPath = join(root, 'docs/governance', `SELF_UPGRADE_REPORT_${date}.md`);

  // Run QA loop to get current status
  const qaResult = runQALoop(root);

  // Get git stats
  let commitCount = 0;
  let filesChanged = 0;
  try {
    commitCount = parseInt(execSync('git log --oneline -10', { cwd: root, encoding: 'utf8' }).trim().split('\n').length.toString());
    filesChanged = parseInt(execSync('git diff --stat HEAD~10 2>/dev/null | tail -1 | grep -oE "[0-9]+ file" | grep -oE "[0-9]+" || echo 0', { cwd: root, encoding: 'utf8' }).trim() || '0');
  } catch {
    // git not available
  }

  const overall = qaResult.allGreen ? '✅ ALL GREEN' : '❌ HAS FAILURES';

  const report = [
    `# Self-Upgrade Report — ${date}`,
    '',
    `**Generated:** ${new Date().toISOString()}`,
    `**Overall:** ${overall}`,
    '',
    '## Summary',
    '',
    '| Metric | Value |',
    '|--------|-------|',
    `| Commits (last 10) | ${commitCount} |`,
    `| Files changed | ${filesChanged} |`,
    '',
    '## Verification',
    '',
    '| Check | Result | Detail | Duration |',
    '|-------|--------|--------|----------|',
    ...qaResult.results.map((r) => `| ${r.step} | ${r.passed ? '✅ PASS' : '❌ FAIL'} | ${r.detail} | ${r.durationMs}ms |`),
    '',
    '## Risk Assessment',
    '',
    `- Risk level: ${qaResult.allGreen ? 'LOW' : 'HIGH'}`,
    `- Rollback plan: \`git revert <commit-hash>\``,
    '',
    '---',
    'Generated by @nai/qa-loop',
  ].join('\n');

  writeFileSync(reportPath, report);

  // Append to history
  const historyPath = join(root, 'docs/governance/SELF_UPGRADE_HISTORY.md');
  const historyRow = `| ${date} | Self-upgrade cycle | ${commitCount} | ${filesChanged} | ${qaResult.results[0]?.passed ? '✅ PASS' : '❌ FAIL'} | ${qaResult.results[1]?.passed ? '✅ PASS' : '❌ FAIL'} | ${qaResult.results[2]?.passed ? '✅ PASS' : '❌ FAIL'} | ${qaResult.results[3]?.passed ? '✅ PASS' : '❌ FAIL'} | ${overall} | [link](SELF_UPGRADE_REPORT_${date}.md) |\n`;

  if (!existsSync(historyPath)) {
    writeFileSync(historyPath, '# Self-Upgrade History\n\n| Date | Event | Commits | Files | Audit | Typecheck | Build | Test | Overall | Report |\n|------|-------|---------|-------|-------|-----------|-------|------|---------|--------|\n');
  }
  appendFileSync(historyPath, historyRow);

  return reportPath;
}

// ============================================================
// Package info
// ============================================================

export const PACKAGE_INFO = {
  name: '@nai/qa-loop',
  version: '0.1.0',
  description: 'Programmatic QA Loop — run verification, read history, generate reports',
};
