/**
 * @nai/scholarship — Public API
 */

export type {
  ScholarshipApplication,
  ApplicantProfile,
  IdentityVerification,
  ScholarshipWish,
  WishVisibilityConsent,
  Review,
  ReviewScore,
  Vote,
  ConflictDisclosure,
  Sponsorship,
  InvestorProfile,
  InvestorAccessGrant,
  ForumRoom,
  ForumPost,
  ModerationDecision,
  Notification,
  Appeal,
  ApplicationStatus,
  ForumPostStatus,
  WishVisibility,
  VerificationType,
  VerificationStatus,
  InvestorRole,
  ReviewScoreCriteria,
  SponsorshipType,
  ModerationAction,
  AppealType,
  ApplicationMessage,
  ApplicationDocument,
  StatusTimelineEntry,
  DocumentType,
  ForumComment,
  ForumReport,
  ReportCategory,
  CouncilDecision,
  WaitlistEntry,
  ScoringRubric,
  ScholarshipEntitlement,
  Cohort,
  EntitlementEvent,
} from './types';

export { SCORING_RUBRIC, COUNCIL_CONFIG, ENTITLEMENT_LIFECYCLE } from './types';

export {
  SCHOLARSHIP_AUDIT_EVENTS,
  SCORING_WEIGHTS,
  SCHOLARSHIP_PROGRAMS,
  MODERATION_PROHIBITED,
} from './types';

export {
  InMemoryScholarshipStore,
  setScholarshipStore,
  getScholarshipStore,
  type ScholarshipStore,
} from './store';

export {
  createApplication,
  updateApplication,
  submitApplication,
  getApplication,
  startVerification,
  completeVerification,
  createWish,
  updateWishVisibility,
  requestWishPublication,
  approveWishPublication,
  rejectWishPublication,
  createReview,
  submitReviewScores,
  submitVote,
  declareConflict,
  createSponsorship,
  markSponsorshipPaid,
  createForumPost,
  submitForumPost,
  moderateForumPost,
  createNotification,
  listNotifications,
  markNotificationRead,
  createAppeal,
  calculateTotalScore,
  sendMessage,
  listMessages,
  uploadDocument,
  listDocuments,
  reviewDocument,
  getApplicationTimeline,
  transitionApplicationStatus,
  createInvestorProfile,
  verifyInvestor,
  grantInvestorAccess,
  revokeInvestorAccess,
  checkInvestorAccess,
  getInvestorApplicationFeed,
  submitReviewWithScores,
  awardScholarship,
  declineScholarship,
  createComment,
  listComments,
  deleteComment,
  reportContent,
  getModerationQueue,
  reviewReport,
  listPublishedPosts,
  makeCouncilDecision,
  getCouncilDecision,
  addToWaitlist,
  listWaitlist,
  offerWaitlistSpot,
  withdrawFromWaitlist,
  grantEntitlement,
  suspendEntitlement,
  restoreEntitlement,
  revokeEntitlement,
  completeEntitlement,
  addLearningPath,
  getUserEntitlements,
  getEntitlementByApplication,
  getEntitlementEvents,
  createCohort,
  listCohorts,
  setRequestContext,
  clearRequestContext,
  setEmailService,
  getEmailService,
} from './service';
