#!/usr/bin/env bash
# tools/self-upgrade-report.sh — Self-Upgrade Report Generator
# Scans git log since last report, categorizes changes, runs QA verification
# Generates: docs/governance/SELF_UPGRADE_REPORT_YYYY-MM-DD.md
# Appends to: docs/governance/SELF_UPGRADE_HISTORY.md

set -euo pipefail
cd "$(dirname "$0")/.."

DATE=$(date -u +"%Y-%m-%d")
TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
REPORT_FILE="docs/governance/SELF_UPGRADE_REPORT_${DATE}.md"
HISTORY_FILE="docs/governance/SELF_UPGRADE_HISTORY.md"

# Find last report date to get commits since
LAST_REPORT=$(ls -1 docs/governance/SELF_UPGRADE_REPORT_*.md 2>/dev/null | sort -r | head -1 || echo "")
if [ -n "$LAST_REPORT" ] && [ "$LAST_REPORT" != "$REPORT_FILE" ]; then
  LAST_DATE=$(echo "$LAST_REPORT" | grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}')
  SINCE_ARG="--since=${LAST_DATE}"
else
  SINCE_ARG="-10"
fi

# Gather git stats
COMMITS=$(git log --oneline $SINCE_ARG 2>/dev/null | wc -l | tr -d ' ')
FILES_CHANGED=$(git diff --stat $SINCE_ARG 2>/dev/null | tail -1 | grep -oE '[0-9]+ file' | grep -oE '[0-9]+' || echo "0")
LINES_ADDED=$(git diff --stat $SINCE_ARG 2>/dev/null | tail -1 | grep -oE '[0-9]+ insertion' | grep -oE '[0-9]+' || echo "0")
LINES_REMOVED=$(git diff --stat $SINCE_ARG 2>/dev/null | tail -1 | grep -oE '[0-9]+ deletion' | grep -oE '[0-9]+' || echo "0")

# Categorize commits
FIX_COMMITS=$(git log --oneline $SINCE_ARG 2>/dev/null | grep -ciE "^.{9}fix" || echo "0")
FEAT_COMMITS=$(git log --oneline $SINCE_ARG 2>/dev/null | grep -ciE "^.{9}feat" || echo "0")
REFACTOR_COMMITS=$(git log --oneline $SINCE_ARG 2>/dev/null | grep -ciE "^.{9}refactor" || echo "0")
DOCS_COMMITS=$(git log --oneline $SINCE_ARG 2>/dev/null | grep -ciE "^.{9}docs" || echo "0")
CHORE_COMMITS=$(git log --oneline $SINCE_ARG 2>/dev/null | grep -ciE "^.{9}chore" || echo "0")

# Run QA verification
AUDIT_STATUS="UNKNOWN"
TYPECHECK_STATUS="UNKNOWN"
BUILD_STATUS="UNKNOWN"
TEST_STATUS="UNKNOWN"

echo "Running QA verification..."
if pnpm run audit:all > /tmp/upgrade-audit.log 2>&1; then
  AUDIT_STATUS="✅ PASS"
else
  AUDIT_STATUS="❌ FAIL"
fi

if pnpm run typecheck > /tmp/upgrade-typecheck.log 2>&1; then
  TYPECHECK_STATUS="✅ PASS"
else
  TYPECHECK_STATUS="❌ FAIL"
fi

if pnpm run build > /tmp/upgrade-build.log 2>&1; then
  BUILD_STATUS="✅ PASS"
else
  BUILD_STATUS="❌ FAIL"
fi

if pnpm run test > /tmp/upgrade-test.log 2>&1; then
  TEST_STATUS="✅ PASS"
else
  TEST_STATUS="❌ FAIL"
fi

OVERALL="✅ ALL GREEN"
[ "$AUDIT_STATUS" = "❌ FAIL" ] && OVERALL="❌ HAS FAILURES"
[ "$TYPECHECK_STATUS" = "❌ FAIL" ] && OVERALL="❌ HAS FAILURES"
[ "$BUILD_STATUS" = "❌ FAIL" ] && OVERALL="❌ HAS FAILURES"
[ "$TEST_STATUS" = "❌ FAIL" ] && OVERALL="❌ HAS FAILURES"

# Generate report
mkdir -p docs/governance

cat > "$REPORT_FILE" << EOF
# Self-Upgrade Report — ${DATE}

**Generated:** ${TIMESTAMP}
**Overall:** ${OVERALL}

## Summary

| Metric | Value |
|--------|-------|
| Commits | ${COMMITS} |
| Files changed | ${FILES_CHANGED} |
| Lines added | ${LINES_ADDED} |
| Lines removed | ${LINES_REMOVED} |
| Fix commits | ${FIX_COMMITS} |
| Feature commits | ${FEAT_COMMITS} |
| Refactor commits | ${REFACTOR_COMMITS} |
| Docs commits | ${DOCS_COMMITS} |
| Chore commits | ${CHORE_COMMITS} |

## Verification

| Check | Result |
|-------|--------|
| audit:all | ${AUDIT_STATUS} |
| typecheck | ${TYPECHECK_STATUS} |
| build | ${BUILD_STATUS} |
| test | ${TEST_STATUS} |

## Recent Commits

\`\`\`
$(git log --oneline $SINCE_ARG 2>/dev/null | head -20)
\`\`\`

## Risk Assessment

- Risk level: LOW (if all green) / HIGH (if any failure)
- Rollback plan: \`git revert <commit-hash>\`

---
Generated by tools/self-upgrade-report.sh
EOF

echo "Report generated: $REPORT_FILE"

# Append to history
if [ ! -f "$HISTORY_FILE" ]; then
  cat > "$HISTORY_FILE" << 'EOF'
# Self-Upgrade History

Append-only log of all self-upgrade events. Each row represents one upgrade cycle.

| Date | Event | Commits | Files | Audit | Typecheck | Build | Test | Overall | Report |
|------|-------|---------|-------|-------|-----------|-------|------|---------|--------|
EOF
fi

{
  echo "| ${DATE} | Self-upgrade cycle | ${COMMITS} | ${FILES_CHANGED} | ${AUDIT_STATUS} | ${TYPECHECK_STATUS} | ${BUILD_STATUS} | ${TEST_STATUS} | ${OVERALL} | [link](SELF_UPGRADE_REPORT_${DATE}.md) |"
} >> "$HISTORY_FILE"

echo "History updated: $HISTORY_FILE"
echo ""
echo "OVERALL: $OVERALL"
